### ISSUE TITLE
Hello, I encountered an issue while running the code. Could you please help me resolve it?

### ISSUE THREAD

**Issue by Angelina-magic** [shangzongjiang/Ada-MSHyper#1]
### RuntimeError in `ASHyper.py`: Tensor size mismatch during `message` operation

---

#### **Description**

I encountered multiple issues when running the `run_longExp.py` script in the `Ada-MSHyper` project. The main problem arises during the forward propagation in the `ASHyper` model, specifically in the `message` method. Here's the detailed traceback:

---

#### **Traceback**

```plaintext
Traceback (most recent call last):
  File "run_longExp.py", line 129, in <module>
    exp.train(setting)
  File "/mnt/nvme1/hmd/Ada-MSHyper/exp/exp_main.py", line 211, in train
    outputs,loss2 = self.model(batch_x, batch_x_mark)
  File "/home/chenjia/miniconda3/envs/Diffusion_TS/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenjia/miniconda3/envs/Diffusion_TS/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/nvme1/hmd/Ada-MSHyper/models/ASHyper.py", line 147, in forward
    output,constrainloss = self.hyconv[i](seq_enc[i], mask)
  File "/home/chenjia/miniconda3/envs/Diffusion_TS/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenjia/miniconda3/envs/Diffusion_TS/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/nvme1/hmd/Ada-MSHyper/models/ASHyper.py", line 392, in forward
    out = self.propagate(hyperedge_index, x=x1, norm=B, alpha=alpha)
  File "/tmp/models.ASHyper_HypergraphConv_propagate_ti_wb4hu.py", line 189, in propagate
    out = self.message(
  File "/mnt/nvme1/hmd/Ada-MSHyper/models/ASHyper.py", line 298, in message
    out=alpha.unsqueeze(-1)*out
RuntimeError: The size of tensor a (16) must match the size of tensor b (96) at non-singleton dimension 1

```

---

#### **Steps to Reproduce**

1. Clone the repository and set up the environment as per the instructions.
2. Run the following command:
   ```bash
   sh ./scripts/Long-range/weather.sh
   ```
3. Observe the error during the execution of the `ASHyper.py` model's forward method.

---

#### **Environment Details**

- OS: Ubuntu 20.04
- Python Version: 3.8
- PyTorch Version: 1.12.1
- CUDA Version: 11.7
- Conda Environment: `Diffusion_TS` as per setup instructions

---

**Comment by houchunyiPhd** [comment]
一样的问题

**Comment by MarvinLong** [comment]
Has anyone solved this problem?

**Comment by Rain920** [comment]
It seems to be the dimension problem of x1, with only one graph construction, so the input of propagate must be (N, M), where N is the number of nodes, so just reshape x1 into (L, B*C), while I'm not sure about the result.

**Comment by Sylus921** [comment]
It appears that the issue with x1's dimensions can be resolved by reshaping x1 from (B, L, C) to (L, B*C), and this approach seems to work effectively.  However, we cannot be entirely certain if this is the most appropriate solution, even though it does function correctly.

**Comment by zixuanxuanxuanxuan** [comment]
> 似乎可以通过将 x1 的维度从 （B， L， C） 重塑为 （L， B*C） 来解决 x1 的维度问题，这种方法似乎很有效。但是，我们无法完全确定这是否是最合适的解决方案，即使它确实正常运行。
可以提供一些具体的代码细节吗，谢谢

**Comment by Sylus921** [comment]
L, BS, C = x1.shape
out = self.propagate(hyperedge_index, x=x1.reshape(L, BS*C), norm=B, alpha=alpha)

But I think this method actually messes up the channel dimension. It just runs, but I'm not sure if it's correct.

**Comment by zixuanxuanxuanxuan** [comment]
> L, BS, C = x1.shape out = self.propagate(hyperedge_index, x=x1.reshape(L, BS*C), norm=B, alpha=alpha)
> 
> But I think this method actually messes up the channel dimension. It just runs, but I'm not sure if it's correct.

![image](https://github.com/user-attachments/assets/706555ea-e682-4c9f-9ebe-ee804e85071e)I've run the modified code and I'm still getting an error, are you experiencing this issue?

**Comment by Sylus921** [comment]
change
`out = norm[edge_index_i].view(-1, 1, 1) * x_j`
into
`out = norm[edge_index_i].view(-1, 1) * x_j`

**Comment by zixuanxuanxuanxuan** [comment]
> 更改为 `out = norm[edge_index_i].view(-1, 1, 1) * x_j` `out = norm[edge_index_i].view(-1, 1) * x_j`

I made changes according to your code and still get the same error, can you send a copy of the code that works in its entirety to my email? 17639353751@163.com, thank you

**Comment by 32ayue** [comment]
> change `out = norm[edge_index_i].view(-1, 1, 1) * x_j` into `out = norm[edge_index_i].view(-1, 1) * x_j`

Dear Developer,
  My project is missing some files, and I sincerely hope to receive your assistance. If you are willing to share a runnable version of the project, you can send the code to my email: liuwenyue_it@sina.com. I would like to express my heartfelt gratitude.

**Comment by lidexf** [comment]
> change `out = norm[edge_index_i].view(-1, 1, 1) * x_j` into `out = norm[edge_index_i].view(-1, 1) * x_j
it doesn't work now, how can i solve this problem?

**Comment by lidexf** [comment]
![Image](https://github.com/user-attachments/assets/5066c58e-4545-47f0-8b00-b37d00143e24)
这个张量维度不一致，无法相乘，在message函数中

**Comment by Rain920** [comment]
Change the node_dim=-2 to node_dim=0 in message_passing.py

**Comment by sopphia2001** [comment]
有人解决这个问题吗？

**Comment by yue-123-xin** [comment]
有人解决了吗，能提供一下能运行的代码吗？yueandxin@126.com非常感谢
